//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("CocheraModelo", "VehiculoClase", "Vehiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MODELO.Vehiculo), "Clase", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MODELO.Clase))]
[assembly: EdmRelationshipAttribute("CocheraModelo", "VehiculoCaja", "Vehiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MODELO.Vehiculo), "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MODELO.Caja))]
[assembly: EdmRelationshipAttribute("CocheraModelo", "DescuentoCaja", "Descuento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MODELO.Descuento), "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MODELO.Caja))]
[assembly: EdmRelationshipAttribute("CocheraModelo", "CajaPagoMensual", "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MODELO.Caja), "PagoMensual", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MODELO.PagoMensual))]
[assembly: EdmRelationshipAttribute("CocheraModelo", "MensualPagoMensual", "Mensual", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MODELO.Mensual), "PagoMensual", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MODELO.PagoMensual))]

#endregion

namespace MODELO
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CocheraModeloContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CocheraModeloContainer usando la cadena de conexión encontrada en la sección 'CocheraModeloContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public CocheraModeloContainer() : base("name=CocheraModeloContainer", "CocheraModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CocheraModeloContainer.
        /// </summary>
        public CocheraModeloContainer(string connectionString) : base(connectionString, "CocheraModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CocheraModeloContainer.
        /// </summary>
        public CocheraModeloContainer(EntityConnection connection) : base(connection, "CocheraModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Vehiculo> Vehiculos
        {
            get
            {
                if ((_Vehiculos == null))
                {
                    _Vehiculos = base.CreateObjectSet<Vehiculo>("Vehiculos");
                }
                return _Vehiculos;
            }
        }
        private ObjectSet<Vehiculo> _Vehiculos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clase> Clases
        {
            get
            {
                if ((_Clases == null))
                {
                    _Clases = base.CreateObjectSet<Clase>("Clases");
                }
                return _Clases;
            }
        }
        private ObjectSet<Clase> _Clases;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Caja> Cajas
        {
            get
            {
                if ((_Cajas == null))
                {
                    _Cajas = base.CreateObjectSet<Caja>("Cajas");
                }
                return _Cajas;
            }
        }
        private ObjectSet<Caja> _Cajas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Sistema> Sistemas
        {
            get
            {
                if ((_Sistemas == null))
                {
                    _Sistemas = base.CreateObjectSet<Sistema>("Sistemas");
                }
                return _Sistemas;
            }
        }
        private ObjectSet<Sistema> _Sistemas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Impresion> Impresiones
        {
            get
            {
                if ((_Impresiones == null))
                {
                    _Impresiones = base.CreateObjectSet<Impresion>("Impresiones");
                }
                return _Impresiones;
            }
        }
        private ObjectSet<Impresion> _Impresiones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Descuento> Descuentos
        {
            get
            {
                if ((_Descuentos == null))
                {
                    _Descuentos = base.CreateObjectSet<Descuento>("Descuentos");
                }
                return _Descuentos;
            }
        }
        private ObjectSet<Descuento> _Descuentos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Mensual> Mensuales
        {
            get
            {
                if ((_Mensuales == null))
                {
                    _Mensuales = base.CreateObjectSet<Mensual>("Mensuales");
                }
                return _Mensuales;
            }
        }
        private ObjectSet<Mensual> _Mensuales;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PagoMensual> PagoMensuales
        {
            get
            {
                if ((_PagoMensuales == null))
                {
                    _PagoMensuales = base.CreateObjectSet<PagoMensual>("PagoMensuales");
                }
                return _PagoMensuales;
            }
        }
        private ObjectSet<PagoMensual> _PagoMensuales;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Recordatorio> Recordatorios
        {
            get
            {
                if ((_Recordatorios == null))
                {
                    _Recordatorios = base.CreateObjectSet<Recordatorio>("Recordatorios");
                }
                return _Recordatorios;
            }
        }
        private ObjectSet<Recordatorio> _Recordatorios;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Vehiculos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVehiculos(Vehiculo vehiculo)
        {
            base.AddObject("Vehiculos", vehiculo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clases. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClases(Clase clase)
        {
            base.AddObject("Clases", clase);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cajas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCajas(Caja caja)
        {
            base.AddObject("Cajas", caja);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Sistemas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSistemas(Sistema sistema)
        {
            base.AddObject("Sistemas", sistema);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Impresiones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToImpresiones(Impresion impresion)
        {
            base.AddObject("Impresiones", impresion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Descuentos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDescuentos(Descuento descuento)
        {
            base.AddObject("Descuentos", descuento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Mensuales. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMensuales(Mensual mensual)
        {
            base.AddObject("Mensuales", mensual);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PagoMensuales. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPagoMensuales(PagoMensual pagoMensual)
        {
            base.AddObject("PagoMensuales", pagoMensual);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Recordatorios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecordatorios(Recordatorio recordatorio)
        {
            base.AddObject("Recordatorios", recordatorio);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Caja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Caja : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Caja.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="total">Valor inicial de la propiedad Total.</param>
        public static Caja CreateCaja(global::System.Int32 id, global::System.Decimal total)
        {
            Caja caja = new Caja();
            caja.Id = id;
            caja.Total = total;
            return caja;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Decimal _Total;
        partial void OnTotalChanging(global::System.Decimal value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaHoraApertura
        {
            get
            {
                return _FechaHoraApertura;
            }
            set
            {
                OnFechaHoraAperturaChanging(value);
                ReportPropertyChanging("FechaHoraApertura");
                _FechaHoraApertura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHoraApertura");
                OnFechaHoraAperturaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaHoraApertura;
        partial void OnFechaHoraAperturaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaHoraAperturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaHoraCierre
        {
            get
            {
                return _FechaHoraCierre;
            }
            set
            {
                OnFechaHoraCierreChanging(value);
                ReportPropertyChanging("FechaHoraCierre");
                _FechaHoraCierre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHoraCierre");
                OnFechaHoraCierreChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaHoraCierre;
        partial void OnFechaHoraCierreChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaHoraCierreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NroCaja
        {
            get
            {
                return _NroCaja;
            }
            set
            {
                OnNroCajaChanging(value);
                ReportPropertyChanging("NroCaja");
                _NroCaja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NroCaja");
                OnNroCajaChanged();
            }
        }
        private Nullable<global::System.Int32> _NroCaja;
        partial void OnNroCajaChanging(Nullable<global::System.Int32> value);
        partial void OnNroCajaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "VehiculoCaja", "Vehiculo")]
        public EntityCollection<Vehiculo> Vehiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vehiculo>("CocheraModelo.VehiculoCaja", "Vehiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vehiculo>("CocheraModelo.VehiculoCaja", "Vehiculo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "DescuentoCaja", "Descuento")]
        public EntityCollection<Descuento> Descuento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Descuento>("CocheraModelo.DescuentoCaja", "Descuento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Descuento>("CocheraModelo.DescuentoCaja", "Descuento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "CajaPagoMensual", "PagoMensual")]
        public EntityCollection<PagoMensual> PagoMensual
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoMensual>("CocheraModelo.CajaPagoMensual", "PagoMensual");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoMensual>("CocheraModelo.CajaPagoMensual", "PagoMensual", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Clase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clase : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clase.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="precioHora">Valor inicial de la propiedad PrecioHora.</param>
        /// <param name="precioMediaEstadia">Valor inicial de la propiedad PrecioMediaEstadia.</param>
        /// <param name="precioEstadia">Valor inicial de la propiedad PrecioEstadia.</param>
        public static Clase CreateClase(global::System.Int32 id, global::System.String codigo, global::System.Decimal precioHora, global::System.Decimal precioMediaEstadia, global::System.Decimal precioEstadia)
        {
            Clase clase = new Clase();
            clase.id = id;
            clase.Codigo = codigo;
            clase.PrecioHora = precioHora;
            clase.PrecioMediaEstadia = precioMediaEstadia;
            clase.PrecioEstadia = precioEstadia;
            return clase;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrecioHora
        {
            get
            {
                return _PrecioHora;
            }
            set
            {
                OnPrecioHoraChanging(value);
                ReportPropertyChanging("PrecioHora");
                _PrecioHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioHora");
                OnPrecioHoraChanged();
            }
        }
        private global::System.Decimal _PrecioHora;
        partial void OnPrecioHoraChanging(global::System.Decimal value);
        partial void OnPrecioHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrecioMediaEstadia
        {
            get
            {
                return _PrecioMediaEstadia;
            }
            set
            {
                OnPrecioMediaEstadiaChanging(value);
                ReportPropertyChanging("PrecioMediaEstadia");
                _PrecioMediaEstadia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioMediaEstadia");
                OnPrecioMediaEstadiaChanged();
            }
        }
        private global::System.Decimal _PrecioMediaEstadia;
        partial void OnPrecioMediaEstadiaChanging(global::System.Decimal value);
        partial void OnPrecioMediaEstadiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrecioEstadia
        {
            get
            {
                return _PrecioEstadia;
            }
            set
            {
                OnPrecioEstadiaChanging(value);
                ReportPropertyChanging("PrecioEstadia");
                _PrecioEstadia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioEstadia");
                OnPrecioEstadiaChanged();
            }
        }
        private global::System.Decimal _PrecioEstadia;
        partial void OnPrecioEstadiaChanging(global::System.Decimal value);
        partial void OnPrecioEstadiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TiempoCambioEstadia
        {
            get
            {
                return _TiempoCambioEstadia;
            }
            set
            {
                OnTiempoCambioEstadiaChanging(value);
                ReportPropertyChanging("TiempoCambioEstadia");
                _TiempoCambioEstadia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TiempoCambioEstadia");
                OnTiempoCambioEstadiaChanged();
            }
        }
        private Nullable<global::System.Int32> _TiempoCambioEstadia;
        partial void OnTiempoCambioEstadiaChanging(Nullable<global::System.Int32> value);
        partial void OnTiempoCambioEstadiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinutosTolerancia
        {
            get
            {
                return _MinutosTolerancia;
            }
            set
            {
                OnMinutosToleranciaChanging(value);
                ReportPropertyChanging("MinutosTolerancia");
                _MinutosTolerancia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinutosTolerancia");
                OnMinutosToleranciaChanged();
            }
        }
        private Nullable<global::System.Int32> _MinutosTolerancia = 0;
        partial void OnMinutosToleranciaChanging(Nullable<global::System.Int32> value);
        partial void OnMinutosToleranciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo = true;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "VehiculoClase", "Vehiculo")]
        public EntityCollection<Vehiculo> Vehiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vehiculo>("CocheraModelo.VehiculoClase", "Vehiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vehiculo>("CocheraModelo.VehiculoClase", "Vehiculo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Descuento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Descuento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Descuento.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        public static Descuento CreateDescuento(global::System.Int32 id, global::System.Decimal monto)
        {
            Descuento descuento = new Descuento();
            descuento.id = id;
            descuento.Monto = monto;
            return descuento;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "DescuentoCaja", "Caja")]
        public Caja Caja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.DescuentoCaja", "Caja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.DescuentoCaja", "Caja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caja> CajaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.DescuentoCaja", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caja>("CocheraModelo.DescuentoCaja", "Caja", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Impresion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Impresion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Impresion.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="pie5">Valor inicial de la propiedad Pie5.</param>
        public static Impresion CreateImpresion(global::System.Int32 codigo, global::System.String descripcion, global::System.String pie5)
        {
            Impresion impresion = new Impresion();
            impresion.Codigo = codigo;
            impresion.Descripcion = descripcion;
            impresion.Pie5 = pie5;
            return impresion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                if (_Codigo != value)
                {
                    OnCodigoChanging(value);
                    ReportPropertyChanging("Codigo");
                    _Codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Codigo");
                    OnCodigoChanged();
                }
            }
        }
        private global::System.Int32 _Codigo;
        partial void OnCodigoChanging(global::System.Int32 value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Encabezado1
        {
            get
            {
                return _Encabezado1;
            }
            set
            {
                OnEncabezado1Changing(value);
                ReportPropertyChanging("Encabezado1");
                _Encabezado1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Encabezado1");
                OnEncabezado1Changed();
            }
        }
        private global::System.String _Encabezado1;
        partial void OnEncabezado1Changing(global::System.String value);
        partial void OnEncabezado1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Encabezado2
        {
            get
            {
                return _Encabezado2;
            }
            set
            {
                OnEncabezado2Changing(value);
                ReportPropertyChanging("Encabezado2");
                _Encabezado2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Encabezado2");
                OnEncabezado2Changed();
            }
        }
        private global::System.String _Encabezado2;
        partial void OnEncabezado2Changing(global::System.String value);
        partial void OnEncabezado2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Encabezado3
        {
            get
            {
                return _Encabezado3;
            }
            set
            {
                OnEncabezado3Changing(value);
                ReportPropertyChanging("Encabezado3");
                _Encabezado3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Encabezado3");
                OnEncabezado3Changed();
            }
        }
        private global::System.String _Encabezado3;
        partial void OnEncabezado3Changing(global::System.String value);
        partial void OnEncabezado3Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Encabezado4
        {
            get
            {
                return _Encabezado4;
            }
            set
            {
                OnEncabezado4Changing(value);
                ReportPropertyChanging("Encabezado4");
                _Encabezado4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Encabezado4");
                OnEncabezado4Changed();
            }
        }
        private global::System.String _Encabezado4;
        partial void OnEncabezado4Changing(global::System.String value);
        partial void OnEncabezado4Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Encabezado5
        {
            get
            {
                return _Encabezado5;
            }
            set
            {
                OnEncabezado5Changing(value);
                ReportPropertyChanging("Encabezado5");
                _Encabezado5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Encabezado5");
                OnEncabezado5Changed();
            }
        }
        private global::System.String _Encabezado5;
        partial void OnEncabezado5Changing(global::System.String value);
        partial void OnEncabezado5Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pie1
        {
            get
            {
                return _Pie1;
            }
            set
            {
                OnPie1Changing(value);
                ReportPropertyChanging("Pie1");
                _Pie1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pie1");
                OnPie1Changed();
            }
        }
        private global::System.String _Pie1;
        partial void OnPie1Changing(global::System.String value);
        partial void OnPie1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pie2
        {
            get
            {
                return _Pie2;
            }
            set
            {
                OnPie2Changing(value);
                ReportPropertyChanging("Pie2");
                _Pie2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pie2");
                OnPie2Changed();
            }
        }
        private global::System.String _Pie2;
        partial void OnPie2Changing(global::System.String value);
        partial void OnPie2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pie3
        {
            get
            {
                return _Pie3;
            }
            set
            {
                OnPie3Changing(value);
                ReportPropertyChanging("Pie3");
                _Pie3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pie3");
                OnPie3Changed();
            }
        }
        private global::System.String _Pie3;
        partial void OnPie3Changing(global::System.String value);
        partial void OnPie3Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pie4
        {
            get
            {
                return _Pie4;
            }
            set
            {
                OnPie4Changing(value);
                ReportPropertyChanging("Pie4");
                _Pie4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pie4");
                OnPie4Changed();
            }
        }
        private global::System.String _Pie4;
        partial void OnPie4Changing(global::System.String value);
        partial void OnPie4Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pie5
        {
            get
            {
                return _Pie5;
            }
            set
            {
                OnPie5Changing(value);
                ReportPropertyChanging("Pie5");
                _Pie5 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pie5");
                OnPie5Changed();
            }
        }
        private global::System.String _Pie5;
        partial void OnPie5Changing(global::System.String value);
        partial void OnPie5Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Mensual")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mensual : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Mensual.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="fechaAlta">Valor inicial de la propiedad FechaAlta.</param>
        public static Mensual CreateMensual(global::System.Int32 id, global::System.Int32 codigo, global::System.DateTime fechaAlta)
        {
            Mensual mensual = new Mensual();
            mensual.id = id;
            mensual.Codigo = codigo;
            mensual.FechaAlta = fechaAlta;
            return mensual;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreApellido
        {
            get
            {
                return _NombreApellido;
            }
            set
            {
                OnNombreApellidoChanging(value);
                ReportPropertyChanging("NombreApellido");
                _NombreApellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreApellido");
                OnNombreApellidoChanged();
            }
        }
        private global::System.String _NombreApellido;
        partial void OnNombreApellidoChanging(global::System.String value);
        partial void OnNombreApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vehiculo
        {
            get
            {
                return _Vehiculo;
            }
            set
            {
                OnVehiculoChanging(value);
                ReportPropertyChanging("Vehiculo");
                _Vehiculo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vehiculo");
                OnVehiculoChanged();
            }
        }
        private global::System.String _Vehiculo;
        partial void OnVehiculoChanging(global::System.String value);
        partial void OnVehiculoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                OnPatenteChanging(value);
                ReportPropertyChanging("Patente");
                _Patente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Patente");
                OnPatenteChanged();
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Domicilio
        {
            get
            {
                return _Domicilio;
            }
            set
            {
                OnDomicilioChanging(value);
                ReportPropertyChanging("Domicilio");
                _Domicilio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Domicilio");
                OnDomicilioChanged();
            }
        }
        private global::System.String _Domicilio;
        partial void OnDomicilioChanging(global::System.String value);
        partial void OnDomicilioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomicilioFiscal
        {
            get
            {
                return _DomicilioFiscal;
            }
            set
            {
                OnDomicilioFiscalChanging(value);
                ReportPropertyChanging("DomicilioFiscal");
                _DomicilioFiscal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomicilioFiscal");
                OnDomicilioFiscalChanged();
            }
        }
        private global::System.String _DomicilioFiscal;
        partial void OnDomicilioFiscalChanging(global::System.String value);
        partial void OnDomicilioFiscalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUIL
        {
            get
            {
                return _CUIL;
            }
            set
            {
                OnCUILChanging(value);
                ReportPropertyChanging("CUIL");
                _CUIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CUIL");
                OnCUILChanged();
            }
        }
        private global::System.String _CUIL;
        partial void OnCUILChanging(global::System.String value);
        partial void OnCUILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoFactura
        {
            get
            {
                return _TipoFactura;
            }
            set
            {
                OnTipoFacturaChanging(value);
                ReportPropertyChanging("TipoFactura");
                _TipoFactura = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoFactura");
                OnTipoFacturaChanged();
            }
        }
        private global::System.String _TipoFactura;
        partial void OnTipoFacturaChanging(global::System.String value);
        partial void OnTipoFacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.Int32 _Codigo;
        partial void OnCodigoChanging(global::System.Int32 value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo = true;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioSugerido
        {
            get
            {
                return _PrecioSugerido;
            }
            set
            {
                OnPrecioSugeridoChanging(value);
                ReportPropertyChanging("PrecioSugerido");
                _PrecioSugerido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioSugerido");
                OnPrecioSugeridoChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioSugerido;
        partial void OnPrecioSugeridoChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioSugeridoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoMensual
        {
            get
            {
                return _TipoMensual;
            }
            set
            {
                OnTipoMensualChanging(value);
                ReportPropertyChanging("TipoMensual");
                _TipoMensual = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoMensual");
                OnTipoMensualChanged();
            }
        }
        private global::System.String _TipoMensual;
        partial void OnTipoMensualChanging(global::System.String value);
        partial void OnTipoMensualChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return _FechaAlta;
            }
            set
            {
                OnFechaAltaChanging(value);
                ReportPropertyChanging("FechaAlta");
                _FechaAlta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaAlta");
                OnFechaAltaChanged();
            }
        }
        private global::System.DateTime _FechaAlta;
        partial void OnFechaAltaChanging(global::System.DateTime value);
        partial void OnFechaAltaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaBaja
        {
            get
            {
                return _FechaBaja;
            }
            set
            {
                OnFechaBajaChanging(value);
                ReportPropertyChanging("FechaBaja");
                _FechaBaja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaBaja");
                OnFechaBajaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaBaja;
        partial void OnFechaBajaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaBajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            set
            {
                OnObservacionesChanging(value);
                ReportPropertyChanging("Observaciones");
                _Observaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observaciones");
                OnObservacionesChanged();
            }
        }
        private global::System.String _Observaciones;
        partial void OnObservacionesChanging(global::System.String value);
        partial void OnObservacionesChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "MensualPagoMensual", "PagoMensual")]
        public EntityCollection<PagoMensual> PagoMensual
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoMensual>("CocheraModelo.MensualPagoMensual", "PagoMensual");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoMensual>("CocheraModelo.MensualPagoMensual", "PagoMensual", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="PagoMensual")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoMensual : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PagoMensual.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        public static PagoMensual CreatePagoMensual(global::System.Int32 id, global::System.DateTime fecha, global::System.Decimal monto)
        {
            PagoMensual pagoMensual = new PagoMensual();
            pagoMensual.id = id;
            pagoMensual.Fecha = fecha;
            pagoMensual.Monto = monto;
            return pagoMensual;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MesSaldado
        {
            get
            {
                return _MesSaldado;
            }
            set
            {
                OnMesSaldadoChanging(value);
                ReportPropertyChanging("MesSaldado");
                _MesSaldado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MesSaldado");
                OnMesSaldadoChanged();
            }
        }
        private Nullable<global::System.Int32> _MesSaldado;
        partial void OnMesSaldadoChanging(Nullable<global::System.Int32> value);
        partial void OnMesSaldadoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "CajaPagoMensual", "Caja")]
        public Caja Caja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.CajaPagoMensual", "Caja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.CajaPagoMensual", "Caja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caja> CajaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.CajaPagoMensual", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caja>("CocheraModelo.CajaPagoMensual", "Caja", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "MensualPagoMensual", "Mensual")]
        public Mensual Mensual
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mensual>("CocheraModelo.MensualPagoMensual", "Mensual").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mensual>("CocheraModelo.MensualPagoMensual", "Mensual").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mensual> MensualReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mensual>("CocheraModelo.MensualPagoMensual", "Mensual");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mensual>("CocheraModelo.MensualPagoMensual", "Mensual", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Recordatorio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recordatorio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Recordatorio.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Recordatorio CreateRecordatorio(global::System.Int32 id)
        {
            Recordatorio recordatorio = new Recordatorio();
            recordatorio.id = id;
            return recordatorio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mensaje
        {
            get
            {
                return _Mensaje;
            }
            set
            {
                OnMensajeChanging(value);
                ReportPropertyChanging("Mensaje");
                _Mensaje = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mensaje");
                OnMensajeChanged();
            }
        }
        private global::System.String _Mensaje;
        partial void OnMensajeChanging(global::System.String value);
        partial void OnMensajeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Sistema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sistema : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Sistema.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="nombreImpresora">Valor inicial de la propiedad NombreImpresora.</param>
        /// <param name="codigoCierre">Valor inicial de la propiedad CodigoCierre.</param>
        /// <param name="passwordWeb">Valor inicial de la propiedad passwordWeb.</param>
        public static Sistema CreateSistema(global::System.Int32 id, global::System.String password, global::System.String nombreImpresora, global::System.String codigoCierre, global::System.String passwordWeb)
        {
            Sistema sistema = new Sistema();
            sistema.id = id;
            sistema.password = password;
            sistema.NombreImpresora = nombreImpresora;
            sistema.CodigoCierre = codigoCierre;
            sistema.passwordWeb = passwordWeb;
            return sistema;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreImpresora
        {
            get
            {
                return _NombreImpresora;
            }
            set
            {
                OnNombreImpresoraChanging(value);
                ReportPropertyChanging("NombreImpresora");
                _NombreImpresora = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreImpresora");
                OnNombreImpresoraChanged();
            }
        }
        private global::System.String _NombreImpresora;
        partial void OnNombreImpresoraChanging(global::System.String value);
        partial void OnNombreImpresoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumeracionTickets
        {
            get
            {
                return _NumeracionTickets;
            }
            set
            {
                OnNumeracionTicketsChanging(value);
                ReportPropertyChanging("NumeracionTickets");
                _NumeracionTickets = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumeracionTickets");
                OnNumeracionTicketsChanged();
            }
        }
        private Nullable<global::System.Int32> _NumeracionTickets = 0;
        partial void OnNumeracionTicketsChanging(Nullable<global::System.Int32> value);
        partial void OnNumeracionTicketsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumeracionCajas
        {
            get
            {
                return _NumeracionCajas;
            }
            set
            {
                OnNumeracionCajasChanging(value);
                ReportPropertyChanging("NumeracionCajas");
                _NumeracionCajas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumeracionCajas");
                OnNumeracionCajasChanged();
            }
        }
        private Nullable<global::System.Int32> _NumeracionCajas = 0;
        partial void OnNumeracionCajasChanging(Nullable<global::System.Int32> value);
        partial void OnNumeracionCajasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CheckSiempreTOP
        {
            get
            {
                return _CheckSiempreTOP;
            }
            set
            {
                OnCheckSiempreTOPChanging(value);
                ReportPropertyChanging("CheckSiempreTOP");
                _CheckSiempreTOP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckSiempreTOP");
                OnCheckSiempreTOPChanged();
            }
        }
        private global::System.Boolean _CheckSiempreTOP = false;
        partial void OnCheckSiempreTOPChanging(global::System.Boolean value);
        partial void OnCheckSiempreTOPChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CheckSiempreMaximizado
        {
            get
            {
                return _CheckSiempreMaximizado;
            }
            set
            {
                OnCheckSiempreMaximizadoChanging(value);
                ReportPropertyChanging("CheckSiempreMaximizado");
                _CheckSiempreMaximizado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckSiempreMaximizado");
                OnCheckSiempreMaximizadoChanged();
            }
        }
        private global::System.Boolean _CheckSiempreMaximizado = false;
        partial void OnCheckSiempreMaximizadoChanging(global::System.Boolean value);
        partial void OnCheckSiempreMaximizadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CheckCodigoCerrar
        {
            get
            {
                return _CheckCodigoCerrar;
            }
            set
            {
                OnCheckCodigoCerrarChanging(value);
                ReportPropertyChanging("CheckCodigoCerrar");
                _CheckCodigoCerrar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckCodigoCerrar");
                OnCheckCodigoCerrarChanged();
            }
        }
        private global::System.Boolean _CheckCodigoCerrar = true;
        partial void OnCheckCodigoCerrarChanging(global::System.Boolean value);
        partial void OnCheckCodigoCerrarChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodigoCierre
        {
            get
            {
                return _CodigoCierre;
            }
            set
            {
                OnCodigoCierreChanging(value);
                ReportPropertyChanging("CodigoCierre");
                _CodigoCierre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodigoCierre");
                OnCodigoCierreChanged();
            }
        }
        private global::System.String _CodigoCierre;
        partial void OnCodigoCierreChanging(global::System.String value);
        partial void OnCodigoCierreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String passwordWeb
        {
            get
            {
                return _passwordWeb;
            }
            set
            {
                OnpasswordWebChanging(value);
                ReportPropertyChanging("passwordWeb");
                _passwordWeb = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("passwordWeb");
                OnpasswordWebChanged();
            }
        }
        private global::System.String _passwordWeb;
        partial void OnpasswordWebChanging(global::System.String value);
        partial void OnpasswordWebChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocheraModelo", Name="Vehiculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehiculo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Vehiculo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="patente">Valor inicial de la propiedad Patente.</param>
        /// <param name="fechaHoraEntrada">Valor inicial de la propiedad FechaHoraEntrada.</param>
        /// <param name="nroTicket">Valor inicial de la propiedad NroTicket.</param>
        public static Vehiculo CreateVehiculo(global::System.Int32 id, global::System.String patente, global::System.DateTime fechaHoraEntrada, global::System.Int32 nroTicket)
        {
            Vehiculo vehiculo = new Vehiculo();
            vehiculo.id = id;
            vehiculo.Patente = patente;
            vehiculo.FechaHoraEntrada = fechaHoraEntrada;
            vehiculo.NroTicket = nroTicket;
            return vehiculo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DuplicadoNro
        {
            get
            {
                return _DuplicadoNro;
            }
            set
            {
                OnDuplicadoNroChanging(value);
                ReportPropertyChanging("DuplicadoNro");
                _DuplicadoNro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DuplicadoNro");
                OnDuplicadoNroChanged();
            }
        }
        private global::System.String _DuplicadoNro = "1";
        partial void OnDuplicadoNroChanging(global::System.String value);
        partial void OnDuplicadoNroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                OnPatenteChanging(value);
                ReportPropertyChanging("Patente");
                _Patente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Patente");
                OnPatenteChanged();
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado = "Activo";
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaHoraEntrada
        {
            get
            {
                return _FechaHoraEntrada;
            }
            set
            {
                OnFechaHoraEntradaChanging(value);
                ReportPropertyChanging("FechaHoraEntrada");
                _FechaHoraEntrada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHoraEntrada");
                OnFechaHoraEntradaChanged();
            }
        }
        private global::System.DateTime _FechaHoraEntrada;
        partial void OnFechaHoraEntradaChanging(global::System.DateTime value);
        partial void OnFechaHoraEntradaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaHoraSalida
        {
            get
            {
                return _FechaHoraSalida;
            }
            set
            {
                OnFechaHoraSalidaChanging(value);
                ReportPropertyChanging("FechaHoraSalida");
                _FechaHoraSalida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHoraSalida");
                OnFechaHoraSalidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaHoraSalida;
        partial void OnFechaHoraSalidaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaHoraSalidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NroTicket
        {
            get
            {
                return _NroTicket;
            }
            set
            {
                OnNroTicketChanging(value);
                ReportPropertyChanging("NroTicket");
                _NroTicket = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NroTicket");
                OnNroTicketChanged();
            }
        }
        private global::System.Int32 _NroTicket;
        partial void OnNroTicketChanging(global::System.Int32 value);
        partial void OnNroTicketChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "VehiculoClase", "Clase")]
        public Clase Clase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clase>("CocheraModelo.VehiculoClase", "Clase").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clase>("CocheraModelo.VehiculoClase", "Clase").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clase> ClaseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clase>("CocheraModelo.VehiculoClase", "Clase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clase>("CocheraModelo.VehiculoClase", "Clase", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocheraModelo", "VehiculoCaja", "Caja")]
        public Caja Caja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.VehiculoCaja", "Caja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.VehiculoCaja", "Caja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caja> CajaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("CocheraModelo.VehiculoCaja", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caja>("CocheraModelo.VehiculoCaja", "Caja", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
